apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: soft-tenant-controller-manager-metrics-service
spec:
  ports:
  - name: https
    port: 8443
    targetPort: https
  selector:
    {{- include "soft-tenant-operator.selectorLabels" . | nindent 4 }}