# permissions for end users to view clusternamespacetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusternamespacetemplate-viewer-role
rules:
- apiGroups:
  - multitenant.mstech.com.cn
  resources:
  - clusternamespacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multitenant.mstech.com.cn
  resources:
  - clusternamespacetemplates/status
  verbs:
  - get
