# permissions for end users to edit clusternamespacetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: clusternamespacetemplate-editor-role
rules:
- apiGroups:
  - multitenant.mstech.com.cn
  resources:
  - clusternamespacetemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - multitenant.mstech.com.cn
  resources:
  - clusternamespacetemplates/status
  verbs:
  - get
