# permissions for end users to view namespacetemplates.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespacetemplate-viewer-role
rules:
- apiGroups:
  - multitenant.mstech.com.cn
  resources:
  - namespacetemplates
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - multitenant.mstech.com.cn
  resources:
  - namespacetemplates/status
  verbs:
  - get
